#!/bin/bash -eu

source ~/.zshenv

PORT=6780
dir=$(dirname $0)

echo "Starting shell-server on port ${PORT}..."

# it must be an absolute path, otherwise it won't work on Mac via Automator
/opt/homebrew/bin/php -S 0.0.0.0:${PORT} -t "${dir}" 2>&1 || echo "Error, not started."; exit 1
